/**
 * Application configuration.
 *
 * Precedence (highest first):
 * 1. Runtime config `window.__WORKHUB_CONFIG__` from `/config.js`, generated by
 *    `docker-entrypoint.sh` at container start (change without rebuilding the image).
 * 2. Build-time `VITE_*` variables (`.env`, Docker build args).
 * 3. Built-in defaults.
 * Empty strings are treated as "not set".
 */
export interface ApiConfig {
  keycloakUrl: string
  realm: string
  clientId: string
  apiUrl: string
  defaultSiteId: number
  /** Refresh the access token this many ms before it expires. */
  tokenRefreshBuffer: number
}

type EnvLike = Partial<Record<keyof ImportMetaEnv, string | undefined>>

function runtimeConfig(): WorkHubRuntimeConfig {
  if (typeof window === 'undefined') return {}
  return window.__WORKHUB_CONFIG__ ?? {}
}

function pick(...candidates: Array<string | undefined>): string {
  for (const value of candidates) {
    const trimmed = value?.trim()
    if (trimmed) return trimmed
  }
  return ''
}

export function buildApiConfig(
  runtime: WorkHubRuntimeConfig = runtimeConfig(),
  env: EnvLike = import.meta.env
): ApiConfig {
  return {
    keycloakUrl: pick(runtime.KEYCLOAK_URL, env.VITE_KEYCLOAK_URL, 'http://localhost:8080'),
    realm: pick(runtime.KEYCLOAK_REALM, env.VITE_KEYCLOAK_REALM, 'gb-realm'),
    clientId: pick(runtime.KEYCLOAK_CLIENT_ID, env.VITE_KEYCLOAK_CLIENT_ID, 'berlink-client'),
    apiUrl: pick(runtime.API_URL, env.VITE_API_URL, '/api'),
    defaultSiteId: parseInt(pick(runtime.DEFAULT_SITE_ID, env.VITE_DEFAULT_SITE_ID, '1'), 10),
    tokenRefreshBuffer: 60000,
  }
}

export const API_CONFIG: ApiConfig = buildApiConfig()

export const STORAGE_KEYS = {
  accessToken: 'workhub_access_token',
  refreshToken: 'workhub_refresh_token',
  tokenExpiry: 'workhub_token_expiry',
  user: 'workhub_user',
  lastSite: 'workhub_last_site',
  lastYard: 'workhub_last_yard',
  uiPreferences: 'workhub_ui_preferences',
}
